routes/web.php
<?php
// Redirect to 404 page
Route::name('errors.404')->get('admincp/errors/404',function(){
	return view('404');
});

Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');

app/Models/Post/Post.php
<?php

namespace App\Models\Post;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Translator;
use Carbon\Carbon;

class Post extends Model
{

    use Translator;
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'posts';

    protected $primaryKey = 'id';
    
    protected $fillable = [
        'title',
        'alias',
        'description',
        'content', 
        'seo_title', 
        'seo_description',
        'seo_keywords', 
        'admin_id', 
        'user_id',
        'featured_image',
        'view', 
        'published', 
        'featured',
        'pos'
    ];

    public $timestamps = true;
    
    /*
    |--------------------------------------------------------------------------
    | Relationship Methods
    |--------------------------------------------------------------------------
    */
    /**
     * Return Status is published
     *
     * @return QueryBuilder
     */
    public function is_published()
    {
        return $this->published;
    }
    /**
     * Return is Featured
     *
     * @return QueryBuilder
     */
    public function is_featured()
    {
        return $this->featured;
    }
   
    public function categories(){
        return $this->belongsToMany('App\Models\Post\Category','category_post','post_id','category_id')->withTimestamps();
    }

    public function admin(){
        return $this->belongsTo('App\Admin');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Models\Post\Tag','tag_post','post_id','tag_id')->withTimestamps();
    }

    public function link()
    {
        return url(trans('route.posts').'/'.$this->categories[0]->language('alias').'/'.$this->alias);
    }

    public function getCreatedAtAttribute($value){
        return Carbon::parse($value);
    }
}

app/Http/Controllers/Admincp/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admincp\Admin;

use App\Http\Requests\Admin\AdminRequest;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Admin\EloquentAdminRepository;
use App\Repositories\Role\EloquentRoleRepository;
use Illuminate\Support\Facades\Redirect;
use Hash;
use Auth;
use View;


class AdminController extends Controller
{
    protected $adminRepository;
    protected $roleRepository;

    public function __construct(
        EloquentAdminRepository $adminRepository,
        EloquentRoleRepository $roleRepository){
        $this->adminRepository = $adminRepository;
        $this->roleRepository = $roleRepository;
        
        // -======= BEGIN : PERMISSONS ==================
        $this->middleware('permission:admins,index', ['only' => ['index']]);
        $this->middleware('permission:admins,create',   ['only' => ['create','store']]);
        $this->middleware('permission:admins,update',   ['only' => ['edit', 'update']]);
        $this->middleware('permission:admins,destroy',   ['only' => ['destroy']]);
        // -======= END : PERMISSONS ====================
        
        
    }

    public function index(Request $request)
    {
        if(Auth::guard('admin')->check()){
            // admins All List
            $admins = $this->adminRepository->getLists(null,null,Auth::guard('admin')->user()->id);
            return view('admincp.admins.index',compact('admins'));
        }
    }

    public function create()
    {
        $roles = $this->roleRepository->getLists();
        return view('admincp.admins.create',compact('roles'));
    }

    public function store(AdminRequest $request)
    {
        //
        $data = $request->alL();
        $data['username'] = trim($data['username']);
        $data['password'] = Hash::make($request->password);
        if($data['profile_image'] == ''){
            $data['profile_image'] = '/user-default.png';
        }
        if($this->adminRepository->createWithLanguage($data)){
            return Redirect::route('admincp.admins.index')->with('alert-success', trans('back-app.add_success'));
        }
        else {
            return Redirect::back()->with('alert-danger', trans('back-app.add_fail'));
        }    
    }

    public function edit($id)
    {
        if(preventUpdateSPAdmin($id)){
            // Check Have Row admin Find By Id
            if($admin = $this->adminRepository->findWithLanguage($id)){
                $roles = isset($admin->role) ? $this->roleRepository->getLists(null,$admin->role->id) : $this->roleRepository->getLists();
                return view('admincp.admins.edit',compact('admin','roles'));        
            }
            else {
                return redirect()->back()->with('alert-danger',trans('back-app.data_not_found'));
            }
        }
        else {
            return redirect()->route('errors.404');
        }
    }

    public function update(AdminRequest $request, $id)
    {
        $data = $request->all();
        $admin = $this->adminRepository->find($id);
        $data['profile_image'] =  $data['profile_image'] ? $data['profile_image'] : $admin->profile_image;
        if(!is_null($data['old_password']) || !is_null($data['password']) || !is_null($data['re_password'])){
            if(! Hash::check( $data['old_password'] ,$admin->password )){
                return redirect()->back()->with('alert-danger','Mật khẩu cũ không đúng');
            }
            else {
                $this->validate($request, [
                    'password' => 'required|min:5',
                    're_password' => 'required|same:password'
                ]);
                $data['password'] = Hash::make($data['password']);
                if($this->adminRepository->updateWithLanguage($id,$data)){
                    return redirect()->back()->with('alert-success',trans('back-app.update_success'));
                }
                return redirect()->back()->with('alert-danger',trans('back-app.update_fail')); 
            }
        }
        else {
            $data['password'] = $admin->password;
            if($this->adminRepository->updateWithLanguage($id,$data)){
                return redirect()->back()->with('alert-success',trans('back-app.update_success'));
            }
            return redirect()->back()->with('alert-danger',trans('back-app.update_fail'));  
        }
    }

    public function destroy($id)
    {
        //
        if($this->adminRepository->deleteWithLanguage($id)){
            return Redirect::back()->with('alert-success', trans('back-app.delete_success'));
        }
        else {
            return Redirect::back()->with('alert-danger',trans('back-app.delete_fail'));
        }
    }

    public function postDisable(Request $request){
        $id_arr = $request->input('id_arr');
        if($this->adminRepository->update($id_arr,['published' => false])){
            session()->flash('alert-success', trans('back-app.update_success'));
            return response()->json('success');
        }   
        
    }

    public function postPublic(Request $request){
        $id_arr = $request->input('id_arr');
        if($this->adminRepository->update($id_arr,['published' => true])){
            session()->flash('alert-success', trans('back-app.update_success'));
            return response()->json('success');
        }     
    }

    public function postDestroys(Request $request){
        $id_arr = $request->input('id_arr');
        if($this->adminRepository->deleteWithLanguage($id_arr)){
            session()->flash('alert-success', trans('back-app.delete_success'));
            return response()->json('success');
        }       
    }
}

app/Http/Controllers/Admincp/Admin/ProfileController.php
<?php

namespace App\Http\Controllers\Admincp\Admin;

use App\Http\Requests\Admin\AdminRequest;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Admin\EloquentAdminRepository;
use Illuminate\Support\Facades\Redirect;
use Auth;
use Hash;
use View;


class ProfileController extends Controller
{
    protected $adminRepository;

    public function __construct(EloquentAdminRepository $adminRepository){
        $this->adminRepository = $adminRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if(Auth::guard('admin')->check()){
            $profile = Auth::guard('admin')->user();
            return view('admincp.admins.profile',compact('profile'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminRequest $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::guard('admin')->check()){
            if(Auth::guard('admin')->user()->id == $id){
                $profile = $this->adminRepository->findWithLanguage(Auth::guard('admin')->user()->id);
                return view('admincp.admins.profile-edit',compact('profile'));
            }   
            else {
                return Redirect::route('404');
            }  
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $profile = $this->adminRepository->find($id);
        if(!is_null($data['old_password']) || !is_null($data['password']) || !is_null($data['re_password'])){
            if(! Hash::check( $data['old_password'] ,$profile->password )){
                return redirect()->back()->with('alert-danger','Mật khẩu cũ không đúng');
            }
            else {
                $this->validate($request, [
                    'password' => 'required|min:5',
                    're_password' => 'required|same:password'
                ]);
                $data['password'] = Hash::make($data['password']);
                if($this->adminRepository->updateWithLanguage($id,$data)){
                    return redirect()->back()->with('alert-success',trans('back-app.update_success'));
                }
                return redirect()->back()->with('alert-danger',trans('back-app.update_fail')); 
            }
        }
        else {
            $data['password'] = $profile->password;
            if($this->adminRepository->updateWithLanguage($id,$data)){
                return redirect()->back()->with('alert-success',trans('back-app.update_success'));
            }
            return redirect()->back()->with('alert-danger',trans('back-app.update_fail'));  
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }
    
}

app/Http/Controllers/Admincp/AdmincpController.php
<?php

namespace App\Http\Controllers\Admincp;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Post\EloquentPostRepository;
use App\Repositories\Product\EloquentProductRepository;
use App\Repositories\Product\EloquentCategoryRepository;
use App\Repositories\User\EloquentUserRepository;
use Auth;

class AdmincpController extends Controller
{
    protected $postRepository;
    protected $productRepository;
    protected $productCateRepository;
    protected $userRepository;

    public function __construct(
        EloquentPostRepository $postRepository,
        EloquentProductRepository $productRepository,
        EloquentCategoryRepository $productCateRepository,
        EloquentUserRepository $userRepository
        ){
        $this->productCateRepository = $productCateRepository;
        $this->productRepository = $productRepository;
        $this->postRepository = $postRepository;
        $this->userRepository = $userRepository;
    }
    public function getDashboard(){
        $product_cate_c = $this->productCateRepository->countDataAddInWeekAgo();
        $product_c = $this->productRepository->countDataAddInWeekAgo();
        $produc_top_v = $this->productRepository->getLists(true,null,10,'view');
        $post_c = $this->postRepository->countDataAddInWeekAgo();
        $post_top_v = $this->postRepository->getLists(true,null,10,'view');
        $user_c = $this->userRepository->countDataAddInWeekAgo();
        return view('admincp.dashboard',[
            'product_cate_c' => $product_cate_c,
            'product_c' => $product_c,
            'produc_top_v' => $produc_top_v,
            'post_c' => $post_c,
            'post_top_v' => $post_top_v,
            'user_c' => $user_c
            ]);
    }

    public function get404page(Request $request)
    {
        return view('admincp.404');
    }

    public function getFilemanager () 
    {
        return view('admincp.filemanager/filemanager');
    }
}

app/Http/Controllers/Admincp/Contact/ContactController.php
<?php

namespace App\Http\Controllers\Admincp\Contact;

use App\Models\Contact\Contact;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;
use Auth;
use View;

class ContactController extends Controller
{

    public function index()
    {
        $contacts = Contact::orderBy('id','desc')->get();
        return view('admincp.contacts.index',compact('contacts'));
    }

    public function updatestatus(Request $request)
    {
        $contact = Contact::find($request->id);

        if (!$contact)
            return response()->json(['error' => 'Contact not found!'], 404);

        if ($contact->update(['published' => true]))
            return response()->json('Update contact success', 200);

    }

    public function destroy($id)
    {
        $contact = Contact::find($id);

        if (!$contact)
            return Redirect::back()->with('alert-danger','Delete Contact Failed!');

        if ($contact->delete())
            return Redirect::back()->with('alert-success','Delete Contact Successfully!');
    }

    public function deleteSelect(Request $request)
    {
        if (!is_array($request->id))
            return response()->json(['error' => 'Param not accept!'], 500);

        if (is_null($request->id))
            return response()->json(['error' => 'Please select contacts for delete!'], 403);

        foreach ($request->id as $id){
            $contact = Contact::find($id);

            if (!$contact)
                continue;

            $contact->delete();
        }
        return response()->json('Delete contacts success', 200);
    }
}

app/Http/Controllers/Admincp/CustomField/CustomFieldController.php
<?php

namespace App\Http\Controllers\Admincp\CustomField;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Customfield\Customfield;
use App\Models\Translation\Translation;
use Artisan;
use Schema;

class CustomFieldController extends Controller
{
    public function index (){
    	$data = Customfield::all();
    	return view('admincp.customfield.index',compact('data'));
    }

    public function create(){
    	return view('admincp.customfield.create');
    }

    public function store (Request $request){
    	$data = $request->all();
    	if(!Customfield::where('table_name',$request->table_name)->where('field',$request->field)->first()){

    		if(Customfield::Create($data)){
                switch ($request->type) {
                    case 'number':
                        Schema::table($request->table_name, function($table) use ($request) {
                            $table->integer($request->field)->nullable();
                        });
                        break;
                    
                    default:
                        Schema::table($request->table_name, function($table) use ($request) {
                            $table->text($request->field)->nullable();
                        });
                        break;
                }
	    		
	    		return redirect()->back()->with('alert-success',trans('back-app.add_success'));
	    	}
    	}else {
    		return redirect()->back()->with('alert-danger',trans('back-app.add_fail'));
    	}
    	
    }

    public function destroy($id){
        if($customfield = Customfield::find($id)){
        	Translation::where('column_name',$customfield->field)->where('table_name',$customfield->table_name)->delete();

        	Schema::table($customfield->table_name, function($table) use ($customfield) {
	           $table->dropColumn($customfield->field);
	        });

        	$customfield->delete();
        	return redirect()->back()->with('alert-success',trans('back-app.delete_success'));
        }
    }
}

resources/views/admincp/404.blade.php
@extends('admincp.layouts.main')
@section('title','404')
@section('content')
<div class="container">
	<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="clearfix">
                    <h1 class="float-left display-3 mr-2">404</h1>
                    <h4 class="pt-1">Oops! You're lost.</h4>
                    <p class="text-muted">The page you are looking for was not found.</p>
                </div>
                <div class="input-prepend input-group">
                    <span class="input-group-addon"><i class="fa fa-search"></i>
                    </span>
                    <input id="prependedInput" class="form-control" size="16" type="text" placeholder="What are you looking for?">
                    <span class="input-group-btn">
                        <button class="btn btn-info" type="button">Search</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admincp/dashboard.blade.php
@extends('admincp.layouts.main')
@section('title',trans('back-app.dashboard'))
@section('content')
<div class="container">
<div class="animated fadeIn">
<div class="card card-block">
<div class="row">
    <!--/.col-->
    <div class="col-md-{{ CAN('products','index') ? '6' : '12' }}">
        <div class="row">
            @if(CAN('products','index'))
                <div class="col-sm-6">
                    <div class="callout callout-warning">
                        <small class="text-muted">Sản phẩm mới</small>
                        <br>
                        <strong class="h4">{{(isset($product_c) ? $product_c : '0')}}</strong>
                    </div>
                </div>
            @endif
            <!--/.col-->
            <div class="col-sm-6">
                <div class="callout callout-success">
                    <small class="text-muted">Tin tới mới</small>
                    <br>
                    <strong class="h4">{{(isset($post_c) ? $post_c : '0')}}</strong>
                </div>
            </div>
            <!--/.col-->
        </div>
        <!--/.row-->
        <hr class="mt-0">
        {{-- Statistics Top Order View --}}
        <div class="card">
            <div class="card-header">
                <i class="icon-check"></i>Lượt xem tin tức
            </div>
            <div class="card-block p-0">
                <div class="tab-content"> 
                    <div class="tab-pane active" id="tickets" aria-expanded="true">
                        <table class="table table-hover mb-0">
                            <thead>
                                <tr>
                                    <th>{{ trans('back-app.status') }}</th>
                                    <th>{{ trans('back-app.created') }}</th>
                                    <th>{{ trans('back-app.title') }}</th>
                                    <th>{{ trans('back-app.view') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(isset($post_top_v))
                                    @foreach($post_top_v as $value )
                                    <tr>
                                        <td>
                                            @if($value->is_published())
                                            <span class="badge badge-success">{{ trans('back-app.public') }}</span>
                                            @else
                                            <span class="badge badge-danger">{{ trans('back-app.disable') }}</span>
                                            @endif
                                        </td>
                                        <td>
                                            {{ date_format($value->created_at, 'l jS F Y') }}
                                        </td>
                                        <td><a href="{{route('admincp.posts.edit',$value->id)}}"> {{ str_limit($value->title,10)}}</a></td>
                                        <td><b>[#{{$value->view}}]</b>
                                        </td>
                                    </tr>
                                    @endforeach
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/.col-->
    <div class="col-md-6">
    	<div class="row">
            @if(CAN('products','index'))
        		<div class="col-sm-6">
        			<div class="callout callout-info">
        				<small class="text-muted">Danh mục sản phẩm mới</small>
        				<br>
        				<strong class="h4">{{(isset($product_cate_c) ? $product_cate_c : '0')}}</strong>
        			</div>
        		</div>
            @endif
    		<!--/.col-->
    		<div class="col-sm-6">
    			<div class="callout callout-danger">
    				<small class="text-muted">Người dùng mới</small>
    				<br>
    				<strong class="h4">{{(isset($user_c) ? $user_c : '0')}}</strong>
    			</div>
    		</div>
    		<!--/.col-->
    	</div>
    	<!--/.row-->
    	<hr class="mt-0">
    	{{-- Statistics Top Product View --}}
        @if(CAN('products','index'))
        	<div class="card">
                <div class="card-header">
                    <i class="icon-check"></i>Lượt xem sản phẩm
                </div>
                <div class="card-block p-0">
                    <div class="tab-content"> 
                        <div class="tab-pane active" id="tickets" aria-expanded="true">
                            <table class="table table-hover mb-0">
                                <thead>
                                    <tr>
                                        <th>{{ trans('back-app.status') }}</th>
                                        <th>{{ trans('back-app.created') }}</th>
                                        <th>{{ trans('back-app.title') }}</th>
                                        <th>{{ trans('back-app.view') }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                	@if(isset($produc_top_v))
                                	@foreach($produc_top_v as $value )
                                    <tr>
                                        <td>
                                        	@if($value->is_published())
                                            <span class="badge badge-success">{{ trans('back-app.public') }}</span>
                                            @else
                                            <span class="badge badge-danger">{{ trans('back-app.disable') }}</span>
                                            @endif
                                        </td>
                                        <td>
                                        	{{date_format($value->created_at, 'l jS F Y')}}
                                        </td>
                                        <td><a href="{{route('admincp.products.edit',$value->id)}}"> {{str_limit($value->vi_title,10)}}</a></td>
                                        <td><b>[#{{$value->view}}]</b>
                                        </td>
                                    </tr>
                                    @endforeach
                                    @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
</div>
<!--/.row-->
</div>
</div>
</div>
@endsection